[tool.ruff]
target-version = "py313"

format.docstring-code-format = true
lint.select = [
  "A",   # flake8-builtins
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "C90", # McCabe cyclomatic complexity
  "E",   # pycodestyle errors
  "F",   # Pyflakes
  "I",   # isort
  "Q",   # flake8-quotes
  "UP",  # pyupgrade
  "W",   # pycodestyle warnings
]
